version: 2.1

variables:
  composer_cache_version: &composer_cache_version v1

orbs:
  eq: equisoft/build-tools@0.0.20

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - eq/phpunit:
          cache-version: *composer_cache_version
          executor: eq/php-7-4
          checkout: true
      - eq/psalm :
          extra-build-args : --no-diff
          executor: eq/php-7-4
          composer-cache-version: *composer_cache_version
          checkout : true
